# Generated by Django 5.1.2 on 2024-11-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ourteam", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ourteampage",
            name="name",
            field=models.TextField(blank=True, default="TOWN OFFICIALS", null=True),
        ),
    ]
