# Generated by Django 5.1.2 on 2024-11-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ourteam", "0002_alter_ourteampage_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ourteampage",
            name="apply_heading",
            field=models.TextField(
                blank=True, default="Become an elected Harmony official", null=True
            ),
        ),
        migrations.AlterField(
            model_name="ourteampage",
            name="button_text",
            field=models.TextField(blank=True, default="Apply Now", null=True),
        ),
        migrations.AlterField(
            model_name="ourteampage",
            name="sub_heading_one",
            field=models.TextField(blank=True, default="Elected Officials", null=True),
        ),
        migrations.AlterField(
            model_name="ourteampage",
            name="sub_heading_two",
            field=models.TextField(
                blank=True, default="Volunteers / Support Staff", null=True
            ),
        ),
    ]
