# Generated by Django 5.1.2 on 2024-11-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_eventpage_event_bg_image_alter_eventpageimages_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpage",
            name="page_name",
            field=models.CharField(
                blank=True, default="EVENTS", max_length=200, null=True
            ),
        ),
    ]
