# Generated by Django 5.1.2 on 2024-11-08 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_eventspage_bottom_button_text_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventpage",
            old_name="event_full_description",
            new_name="bottom_heading",
        ),
        migrations.RenameField(
            model_name="eventpage",
            old_name="event_short_heading",
            new_name="event_details_heading",
        ),
        migrations.AddField(
            model_name="eventpage",
            name="bottom_button_text",
            field=models.TextField(blank=True, default="Contact us", null=True),
        ),
        migrations.AddField(
            model_name="eventpage",
            name="bottom_image_one",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="eventpage",
            name="bottom_image_two",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="eventpage",
            name="bottom_link_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AlterField(
            model_name="eventpage",
            name="button_text",
            field=models.TextField(blank=True, default="Add to Calender", null=True),
        ),
    ]
