# Generated by Django 5.1.2 on 2024-11-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "events",
            "0006_rename_event_full_description_eventpage_bottom_heading_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="eventpageimages",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
