# Generated by Django 5.1.2 on 2024-11-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emergency", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencypagecontent",
            name="name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emergencypagecontent",
            name="short_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
