# Generated by Django 5.1.2 on 2024-11-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emergency", "0002_alter_emergencypagecontent_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="emergencypagecontent",
            old_name="name",
            new_name="service_name_heading",
        ),
        migrations.AddField(
            model_name="emergencypagecontent",
            name="service_sidebar_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
