# Generated by Django 5.1.2 on 2024-11-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "emergency",
            "0003_rename_name_emergencypagecontent_service_name_heading_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="emergencypagecontent",
            name="button_name",
            field=models.TextField(blank=True, default="READ MORE", null=True),
        ),
    ]
