# Generated by Django 5.1.2 on 2024-11-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "interest",
            "0002_rename_interest_description_pointsofinterest_bottom_heading_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointsofinterest",
            name="bottom_button_text",
            field=models.TextField(blank=True, default="Submit your photo", null=True),
        ),
    ]
