# Generated by Django 5.1.2 on 2024-11-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interest", "0003_alter_pointsofinterest_bottom_button_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pointsofinterest",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("schools", "Schools"),
                    ("parks", "Parks"),
                    ("town_hall", "Town Hall"),
                    ("parking_streets", "Parking Streets"),
                ],
                max_length=50,
            ),
        ),
    ]
