# Generated by Django 5.1.2 on 2024-11-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interest", "0006_singlepointsofinterest_bottom_button_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singlepagefeatureddetail",
            name="land_location_text",
            field=models.TextField(
                blank=True, default="Land Drop the pin to see location", null=True
            ),
        ),
    ]
