# Generated by Django 5.1.2 on 2024-11-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interest", "0007_alter_singlepagefeatureddetail_land_location_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="singlepointsofinterest",
            name="back_button_text",
            field=models.TextField(
                blank=True, default="Back to Points of Interest", null=True
            ),
        ),
        migrations.AlterField(
            model_name="singlepointsofinterest",
            name="text",
            field=models.TextField(
                blank=True, default="Drop the pin to see location", null=True
            ),
        ),
    ]
