# Generated by Django 5.1.2 on 2024-11-11 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("land", "0003_singlelandfeatureddetails_and_more"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="singlelandfeatureddetails",
            options={
                "verbose_name": "Singel Page",
                "verbose_name_plural": "Single Pages",
            },
        ),
        migrations.RenameField(
            model_name="singlelandfeatureddetails",
            old_name="small_land_image",
            new_name="land_image",
        ),
        migrations.AddField(
            model_name="singlelandfeatureddetails",
            name="location_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
