# Generated by Django 5.1.2 on 2024-11-11 07:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("land", "0004_alter_singlelandfeatureddetails_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="singlelandfeatureddetails",
            options={
                "verbose_name": "Singel Feature Page",
                "verbose_name_plural": "Single Feature Pages",
            },
        ),
        migrations.DeleteModel(
            name="LandSpot",
        ),
    ]
