# Generated by Django 5.1.2 on 2024-11-05 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0004_party_partyposition"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="singleelectionpage",
            options={
                "verbose_name": "Single Election Page",
                "verbose_name_plural": "Single Election Page",
            },
        ),
    ]
