# Generated by Django 5.1.2 on 2024-11-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0005_alter_singleelectionpage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="electionspage",
            name="party_name",
            field=models.TextField(blank=True, default="ELECTIONS", null=True),
        ),
    ]
