# Generated by Django 5.1.2 on 2024-11-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0006_electionspage_party_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="electionspage",
            name="sub_heading_two",
            field=models.TextField(blank=True, null=True),
        ),
    ]
