# Generated by Django 5.1.2 on 2024-11-06 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0008_rename_party_name_electionspage_page_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="electionpageperson",
            name="re_election_designation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
