# Generated by Django 5.1.2 on 2024-11-07 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0010_electionspage_button_text_three_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="electionspage",
            name="nomination_heading",
            field=models.TextField(
                blank=True,
                default="Apply for the nomination Check the criteria and Eligibility",
                null=True,
            ),
        ),
    ]
