# Generated by Django 5.1.2 on 2024-11-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0011_electionspage_nomination_heading"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleelectionpage",
            name="page_notice",
            field=models.TextField(blank=True, null=True),
        ),
    ]
