# Generated by Django 5.1.2 on 2024-11-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0012_singleelectionpage_page_notice"),
    ]

    operations = [
        migrations.AddField(
            model_name="singleelectionpage",
            name="form_description_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
