# Generated by Django 5.1.2 on 2024-11-11 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesspage",
            name="business_heading",
            field=models.TextField(
                blank=True, default="Why do Business in harmony", null=True
            ),
        ),
    ]
