# Generated by Django 5.1.2 on 2024-11-11 03:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0002_alter_businesspage_business_heading"),
    ]

    operations = [
        migrations.RenameField(
            model_name="businesspage",
            old_name="growth_data_numbes_one",
            new_name="growth_data_number_one",
        ),
        migrations.RenameField(
            model_name="businesspage",
            old_name="growth_data_numbes_three",
            new_name="growth_data_number_three",
        ),
        migrations.RenameField(
            model_name="businesspage",
            old_name="growth_data_numbes_two",
            new_name="growth_data_number_two",
        ),
    ]
