# Generated by Django 5.1.2 on 2024-10-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetings", "0002_meetingpage_meeting_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetingpage",
            name="meeting_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Enter meeting AGENDA"
            ),
        ),
    ]
