# Generated by Django 5.1.2 on 2024-10-30 14:00

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("history", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historypage",
            options={
                "verbose_name": "History Page Content",
                "verbose_name_plural": "History Page Contents",
            },
        ),
        migrations.RenameField(
            model_name="historypage",
            old_name="full_description",
            new_name="content_full_description",
        ),
        migrations.RenameField(
            model_name="historypage",
            old_name="heading",
            new_name="content_short_description",
        ),
        migrations.RemoveField(
            model_name="historypage",
            name="short_description",
        ),
        migrations.AddField(
            model_name="historypage",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historypage",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="historypage",
            name="body",
            field=wagtail.fields.StreamField([], blank=True, block_lookup={}),
        ),
        migrations.CreateModel(
            name="HistoriesPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("button", 4)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {}),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("btn-dark", "Dark"),
                                        ("btn-light", "Light"),
                                        ("btn-link", "Link"),
                                        ("btn-primary", "Primary"),
                                        ("btn-secondary", "Secondary"),
                                    ]
                                },
                            ),
                            2: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            3: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"label": "URL", "required": False},
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("type", 1), ("page", 2), ("url", 3)]],
                                {},
                            ),
                        },
                    ),
                ),
                ("search", models.TextField(blank=True, null=True)),
                (
                    "heading",
                    models.TextField(
                        blank=True, default="History of Harmony", null=True
                    ),
                ),
                ("short_heading", models.TextField(blank=True, null=True)),
                ("short_description", models.TextField(blank=True, null=True)),
                (
                    "cover_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cover image for this page, used in listings and at the top of the page",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Histories Page",
                "verbose_name_plural": "Histories Pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.DeleteModel(
            name="HistoryPageContent",
        ),
    ]
