# Generated by Django 5.1.2 on 2024-10-30 14:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("permits", "0003_formfield"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FormField",
        ),
    ]
