# Generated by Django 5.1.2 on 2024-11-07 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("permits", "0004_delete_formfield"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="permitpage",
            name="permit_button_text",
            field=models.TextField(blank=True, default="Apply Now", null=True),
        ),
        migrations.AddField(
            model_name="permitpage",
            name="permit_link_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
    ]
