# Generated by Django 5.1.2 on 2024-10-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsdetailpage",
            options={
                "verbose_name": "News Detail Page",
                "verbose_name_plural": "News DetailPage",
            },
        ),
        migrations.AlterField(
            model_name="newspageimages",
            name="image_title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
