# Generated by Django 5.1.2 on 2024-10-30 14:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_newsdetailpage_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsdetailpage",
            options={
                "verbose_name": "News Detail Page",
                "verbose_name_plural": "News Detail Page",
            },
        ),
    ]
