# Generated by Django 5.1.2 on 2024-11-07 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_newsdetailpage_date"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newspage",
            old_name="heading",
            new_name="bottom_heading",
        ),
        migrations.AddField(
            model_name="newspage",
            name="bottom_button_text",
            field=models.TextField(blank=True, default="Read more", null=True),
        ),
        migrations.AddField(
            model_name="newspage",
            name="bottom_image_one",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="newspage",
            name="bottom_image_two",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="newspage",
            name="bottom_link_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AlterField(
            model_name="newspage",
            name="name",
            field=models.TextField(blank=True, default="NEWS", null=True),
        ),
    ]
