# Generated by Django 5.1.2 on 2024-11-07 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_rename_heading_newspage_bottom_heading_and_more"),
        ("wagtailimages", "0026_delete_uploadedimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsdetailpage",
            old_name="button_text",
            new_name="bottom_button_text",
        ),
        migrations.RenameField(
            model_name="newsdetailpage",
            old_name="link_page",
            new_name="bottom_link_page",
        ),
        migrations.AddField(
            model_name="newsdetailpage",
            name="bottom_heading",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="newsdetailpage",
            name="bottom_image_one",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="newsdetailpage",
            name="bottom_image_two",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
