# Generated by Django 5.1.2 on 2024-11-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_rename_button_text_newsdetailpage_bottom_button_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsdetailpage",
            name="bottom_button_text",
            field=models.TextField(blank=True, default="History", null=True),
        ),
    ]
