# Generated by Django 5.1.2 on 2024-11-06 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_homepage_park_bgimage_parkslist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="read_page_text",
        ),
        migrations.AddField(
            model_name="homepage",
            name="news_button_text",
            field=models.CharField(
                blank=True, default="Read more", max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="news_heading",
            field=models.CharField(
                blank=True, default="Latest News", max_length=200, null=True
            ),
        ),
    ]
