# Generated by Django 5.1.2 on 2024-11-06 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_remove_homepage_upcoming_event_text_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="history_page_text",
        ),
        migrations.AddField(
            model_name="homepage",
            name="history_page_button_text",
            field=models.CharField(
                blank=True, default="Get the History", max_length=200, null=True
            ),
        ),
    ]
