# Generated by Django 5.1.2 on 2024-11-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_homepage_history_bg_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="team_page_text",
        ),
        migrations.AddField(
            model_name="homepage",
            name="team_page_button_text",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
