# Generated by Django 5.1.2 on 2024-11-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_remove_homepage_team_page_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="team_page_button_text",
            field=models.CharField(
                blank=True, default="See Officials", max_length=200, null=True
            ),
        ),
    ]
